"""Algorithm primitives — searches and recursions, with their working shown.

Every scene built on this module claims a count: binary search finds an item
in log-n steps, Hanoi needs two-to-the-n minus one moves. Those are exactly
the claims an animation fakes by playing the right number of steps, so the
steps themselves are generated and counted here.
"""

from __future__ import annotations

import math
from dataclasses import dataclass


@dataclass
class Probe:
    """One look taken by binary search."""
    lo: int
    hi: int
    mid: int
    value: int
    verdict: str          # "found", "too high", "too low"


def binary_search(items: list[int], target: int) -> list[Probe]:
    """Search, recorded probe by probe.

    ``lo`` and ``hi`` are inclusive, and ``mid`` uses floor division, so the
    trace is reproducible rather than merely plausible -- a scene that shows a
    different midpoint from the one the code would pick is teaching a
    different algorithm.
    """
    lo, hi, out = 0, len(items) - 1, []
    while lo <= hi:
        mid = (lo + hi) // 2
        v = items[mid]
        if v == target:
            out.append(Probe(lo, hi, mid, v, "found"))
            return out
        verdict = "too high" if v > target else "too low"
        out.append(Probe(lo, hi, mid, v, verdict))
        if v > target:
            hi = mid - 1
        else:
            lo = mid + 1
    return out


def verify_binary_search(items: list[int]) -> bool:
    """Every element must be found, and never in more than ceil(log2(n))+1 looks."""
    bound = math.ceil(math.log2(len(items))) + 1
    for t in items:
        probes = binary_search(items, t)
        if not probes or probes[-1].verdict != "found" or len(probes) > bound:
            return False
    return True


def linear_search_cost(items: list[int], target: int) -> int:
    """Looks needed by scanning from the left -- the thing being compared against."""
    return items.index(target) + 1


@dataclass
class Move:
    """One disc moved between pegs."""
    disc: int
    frm: str
    to: str


def hanoi(n: int, frm: str = "A", to: str = "C", via: str = "B") -> list[Move]:
    """Every move, in order, for ``n`` discs.

    Generated by the recursion itself rather than by a formula: move n-1 out
    of the way, move the big one, move n-1 back. The count 2^n - 1 is then a
    fact about the list, which the scene checks, rather than a number it was
    told to display.
    """
    if n == 0:
        return []
    return (hanoi(n - 1, frm, via, to)
            + [Move(n, frm, to)]
            + hanoi(n - 1, via, to, frm))


def verify_hanoi(max_n: int = 12) -> bool:
    """The move list must be legal and exactly 2^n - 1 long.

    Legality is the part worth checking: a shorter list that put a big disc on
    a small one would still look like a solution in a drawing.
    """
    for n in range(1, max_n + 1):
        moves = hanoi(n)
        if len(moves) != 2 ** n - 1:
            return False
        pegs = {"A": list(range(n, 0, -1)), "B": [], "C": []}
        for m in moves:
            if not pegs[m.frm] or pegs[m.frm][-1] != m.disc:
                return False
            if pegs[m.to] and pegs[m.to][-1] < m.disc:
                return False           # a larger disc onto a smaller one
            pegs[m.to].append(pegs[m.frm].pop())
        if pegs["C"] != list(range(n, 0, -1)):
            return False
    return True
